/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as LandingAboutImport } from './routes/landing/about'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LandingAboutRoute = LandingAboutImport.update({
  id: '/landing/about',
  path: '/landing/about',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/landing/about': {
      id: '/landing/about'
      path: '/landing/about'
      fullPath: '/landing/about'
      preLoaderRoute: typeof LandingAboutImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/landing/about': typeof LandingAboutRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landing/about': typeof LandingAboutRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/landing/about': typeof LandingAboutRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/landing/about'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/landing/about'
  id: '__root__' | '/' | '/landing/about'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LandingAboutRoute: typeof LandingAboutRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LandingAboutRoute: LandingAboutRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/landing/about"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/landing/about": {
      "filePath": "landing/about.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
